In [1]:
import numpy as np
import pandas as pd

In [2]:
df =pd.read_csv('student-data.csv')
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  passed      395 non-null    object
dtypes: int64(13), object(18)
memory usage: 95.8+ KB

In [4]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
passed        0
dtype: int64

In [5]:
df['school'].astype('category').value_counts()

school
GP    349
MS     46
Name: count, dtype: int64

In [6]:
df['sex'].astype('category').value_counts()

sex
F    208
M    187
Name: count, dtype: int64

In [7]:
df['address'].astype('category').value_counts()

address
U    307
R     88
Name: count, dtype: int64

In [8]:
df['famsize'].astype('category').value_counts()

famsize
GT3    281
LE3    114
Name: count, dtype: int64

In [9]:
df['Pstatus'].astype('category').value_counts()

Pstatus
T    354
A     41
Name: count, dtype: int64

In [10]:
df['Mjob'].astype('category').value_counts()

Mjob
other       141
services    103
at_home      59
teacher      58
health       34
Name: count, dtype: int64

In [11]:
df['Fjob'].astype('category').value_counts()

Fjob
other       217
services    111
teacher      29
at_home      20
health       18
Name: count, dtype: int64

In [12]:
df['reason'].astype('category').value_counts()

reason
course        145
home          109
reputation    105
other          36
Name: count, dtype: int64

In [13]:
df['guardian'].astype('category').value_counts()

guardian
mother    273
father     90
other      32
Name: count, dtype: int64

In [14]:
df['schoolsup'].astype('category').value_counts()

schoolsup
no     344
yes     51
Name: count, dtype: int64

In [15]:
df['famsup'].astype('category').value_counts()

famsup
yes    242
no     153
Name: count, dtype: int64

In [16]:
df['paid'].astype('category').value_counts()

paid
no     214
yes    181
Name: count, dtype: int64

In [17]:
df['activities'].astype('category').value_counts()

activities
yes    201
no     194
Name: count, dtype: int64

In [18]:
df['nursery'].astype('category').value_counts()

nursery
yes    314
no      81
Name: count, dtype: int64

In [19]:
df['higher'].astype('category').value_counts()

higher
yes    375
no      20
Name: count, dtype: int64

In [20]:
df['internet'].astype('category').value_counts()

internet
yes    329
no      66
Name: count, dtype: int64

In [21]:
df['romantic'].astype('category').value_counts()

romantic
no     263
yes    132
Name: count, dtype: int64

In [22]:
df['passed'].astype('category').value_counts()

passed
yes    265
no     130
Name: count, dtype: int64

**Now let's explain every column in the dataframe**
- `school` : student's school (binary: "GP" or "MS")
- `sex` : student's sex (binary: "F" - female or "M" - male)
- `age` : student's age (numeric: from 15 to 22)
- `address` : student's home address type (binary: "U" - urban or "R" - rural)
- `famsize` : family size (binary: "LE3" - less or equal to 3 or "GT3" - greater than 3)
- `Pstatus` : parent's cohabitation status (binary: "T" - living together or "A" - apart)
- `Medu` : mother's education (numeric: 0 - none,  1 - primary education (4th grade), 2 - 5th to 9th grade, 3 - secondary education or 4 - higher education)
- `Fedu` : father's education (numeric: 0 - none,  1 - primary education (4th grade), 2 - 5th to 9th grade, 3 - secondary education or 4 - higher education)
- `Mjob` : mother's job (nominal: "teacher", "health" care related, civil "services" (e.g. administrative or police), "at_home" or "other")
- `Fjob` : father's job (nominal: "teacher", "health" care related, civil "services" (e.g. administrative or police), "at_home" or "other")
- `reason` : reason to choose this school (nominal: close to "home", school "reputation", "course" preference or "other")
- `guardian` : student's guardian (nominal: "mother", "father" or "other")
- `traveltime` : home to school travel time (numeric: 1 - <15 min., 2 - 15 to 30 min., 3 - 30 min. to 1 hour, or 4 - >1 hour)
- `studytime` : weekly study time (numeric: 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)
- `failures` : number of past class failures (numeric: n if 1<=n<3, else 4)
- `schoolsup` : extra educational support (binary: yes or no)
- `famsup` : family educational support (binary: yes or no)
- `paid` : extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)
- `activities` : extra-curricular activities (binary: yes or no)
- `nursery` : attended nursery school (binary: yes or no)
- `higher` : wants to take higher education (binary: yes or no)
- `internet` : Internet access at home (binary: yes or no)
- `romantic` : with a romantic relationship (binary: yes or no)
- `famrel` : quality of family relationships (numeric: from 1 - very bad to 5 - excellent)
- `freetime` : free time after school (numeric: from 1 - very low to 5 - very high)
- `goout` : going out with friends (numeric: from 1 - very low to 5 - very high)
- `Dalc` : workday alcohol consumption (numeric: from 1 - very low to 5 - very high)
- `Walc` : weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)
- `health` : current health status (numeric: from 1 - very bad to 5 - very good)
- `absences` : number of school absences (numeric: from 0 to 93)

**The last column:**
- `passed` : did the student pass the final exam or not (binary: yes or no)

In [23]:
# mapping strings to numeric values:
def numerical_data():
    df['school'] = df['school'].map({'GP': 0, 'MS': 1})
    df['sex'] = df['sex'].map({'M': 0, 'F': 1})
    df['address'] = df['address'].map({'U': 0, 'R': 1})
    df['famsize'] = df['famsize'].map({'LE3': 0, 'GT3': 1})
    df['Pstatus'] = df['Pstatus'].map({'T': 0, 'A': 1})
    df['Mjob'] = df['Mjob'].map({'teacher': 0, 'health': 1, 'services': 2, 'at_home': 3, 'other': 4})
    df['Fjob'] = df['Fjob'].map({'teacher': 0, 'health': 1, 'services': 2, 'at_home': 3, 'other': 4})
    df['reason'] = df['reason'].map({'home': 0, 'reputation': 1, 'course': 2, 'other': 3})
    df['guardian'] = df['guardian'].map({'mother': 0, 'father': 1, 'other': 2})
    df['schoolsup'] = df['schoolsup'].map({'no': 0, 'yes': 1})
    df['famsup'] = df['famsup'].map({'no': 0, 'yes': 1})
    df['paid'] = df['paid'].map({'no': 0, 'yes': 1})
    df['activities'] = df['activities'].map({'no': 0, 'yes': 1})
    df['nursery'] = df['nursery'].map({'no': 0, 'yes': 1})
    df['higher'] = df['higher'].map({'no': 0, 'yes': 1})
    df['internet'] = df['internet'].map({'no': 0, 'yes': 1})
    df['romantic'] = df['romantic'].map({'no': 0, 'yes' : 1})
    df['passed'] = df['passed'].map({'no': 0, 'yes': 1})

In [24]:
numerical_data()
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,0,1,18,0,1,1,4,4,3,0,...,0,0,4,3,4,1,1,3,6,0
1,0,1,17,0,1,0,1,1,3,4,...,1,0,5,3,3,1,1,3,4,0
2,0,1,15,0,0,0,1,1,3,4,...,1,0,4,3,2,2,3,3,10,1
3,0,1,15,0,1,0,4,2,1,2,...,1,1,3,2,2,1,1,5,2,1
4,0,1,16,0,1,0,3,3,4,4,...,0,0,4,3,2,1,2,5,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,1,0,20,0,0,1,2,2,2,2,...,0,0,5,5,4,4,5,4,11,0
391,1,0,17,0,0,0,3,1,2,2,...,1,0,2,4,5,3,4,2,3,1
392,1,0,21,1,1,0,1,1,4,4,...,0,0,5,5,3,3,3,3,3,0
393,1,0,18,1,0,0,3,2,2,4,...,1,0,4,4,1,3,4,5,0,1
394,1,0,19,0,0,0,1,1,4,3,...,1,0,3,2,3,3,3,5,5,0

In [43]:
df['failures'].astype('category').value_counts()

failures
0    312
1     50
2     17
3     16
Name: count, dtype: int64

In [44]:
df['famrel'].astype('category').value_counts()

famrel
4    195
5    106
3     68
2     18
1      8
Name: count, dtype: int64

In [25]:
# feature scaling will allow the algorithm to converge faster, large data will have same scal
def feature_scaling(df):
    for i in df:
        col = df[i]
        # let's choose columns that have large values
        if(np.max(col)>6):
            Max = max(col)
            Min = min(col)
            mean = np.mean(col)
            col  = (col-mean)/(Max)
            df[i] = col
        elif(np.max(col)<6):
            col = (col-np.min(col))
            col /= np.max(col)
            df[i] = col

In [26]:
# feature_scaling(df)
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,0,1,18,0,1,1,4,4,3,0,...,0,0,4,3,4,1,1,3,6,0
1,0,1,17,0,1,0,1,1,3,4,...,1,0,5,3,3,1,1,3,4,0
2,0,1,15,0,0,0,1,1,3,4,...,1,0,4,3,2,2,3,3,10,1
3,0,1,15,0,1,0,4,2,1,2,...,1,1,3,2,2,1,1,5,2,1
4,0,1,16,0,1,0,3,3,4,4,...,0,0,4,3,2,1,2,5,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,1,0,20,0,0,1,2,2,2,2,...,0,0,5,5,4,4,5,4,11,0
391,1,0,17,0,0,0,3,1,2,2,...,1,0,2,4,5,3,4,2,3,1
392,1,0,21,1,1,0,1,1,4,4,...,0,0,5,5,3,3,3,3,3,0
393,1,0,18,1,0,0,3,2,2,4,...,1,0,4,4,1,3,4,5,0,1
394,1,0,19,0,0,0,1,1,4,3,...,1,0,3,2,3,3,3,5,5,0

In [27]:
df.shape

(395, 31)

<h1>Logistic Regression</h1>

In [28]:
x = df.drop('passed',axis='columns')
x

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences
0,0,1,18,0,1,1,4,4,3,0,...,1,0,0,4,3,4,1,1,3,6
1,0,1,17,0,1,0,1,1,3,4,...,1,1,0,5,3,3,1,1,3,4
2,0,1,15,0,0,0,1,1,3,4,...,1,1,0,4,3,2,2,3,3,10
3,0,1,15,0,1,0,4,2,1,2,...,1,1,1,3,2,2,1,1,5,2
4,0,1,16,0,1,0,3,3,4,4,...,1,0,0,4,3,2,1,2,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,1,0,20,0,0,1,2,2,2,2,...,1,0,0,5,5,4,4,5,4,11
391,1,0,17,0,0,0,3,1,2,2,...,1,1,0,2,4,5,3,4,2,3
392,1,0,21,1,1,0,1,1,4,4,...,1,0,0,5,5,3,3,3,3,3
393,1,0,18,1,0,0,3,2,2,4,...,1,1,0,4,4,1,3,4,5,0
394,1,0,19,0,0,0,1,1,4,3,...,1,1,0,3,2,3,3,3,5,5

In [29]:
y = df['passed'].astype(int)
y

0      0
1      0
2      1
3      1
4      1
      ..
390    0
391    1
392    0
393    1
394    0
Name: passed, Length: 395, dtype: int32

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [31]:
len(X_train)

276

In [32]:
len(X_test)

119

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
LR = LogisticRegression(max_iter = 10000)

In [35]:
LR.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

In [36]:
LR.score(X_test,y_test)

0.6302521008403361

In [37]:
from sklearn.metrics import accuracy_score, f1_score
 

# Initialize variables
max_iterations = 100
best_f1 = 0
best_accuracy = 0
optimal_state = 0

# Search for the best random state
for _ in range(max_iterations):
    random_state = np.random.randint(1, 100000000)
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=random_state)
    
    model = LogisticRegression(C=1, max_iter=1000)
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    
    f1 = f1_score(y_test, y_pred, average='macro')
    accuracy = accuracy_score(y_test, y_pred)
    
    # Update if current iteration has better scores
    if f1 > best_f1 or accuracy > best_accuracy:
        best_f1 = f1
        best_accuracy = accuracy
        optimal_state = random_state

# Train the final model with the optimal random state
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=optimal_state)
final_model = LogisticRegression(C=1, max_iter=1000)
final_model.fit(x_train, y_train)
y_pred = final_model.predict(x_test)

# Final scores
final_f1 = f1_score(y_test, y_pred, average='macro')
final_accuracy = accuracy_score(y_test, y_pred)

print(f"Optimal Random State: {optimal_state}")
print(f"Final Accuracy: {final_accuracy * 100:.2f}%")
print(f"Final F1 Score: {final_f1:.2f}")
print(final_model.score(x_test,y_test))

Optimal Random State: 67732564
Final Accuracy: 76.47%
Final F1 Score: 0.69
0.7647058823529411

In [38]:
final_model.score(x_test,y_test)

0.7647058823529411

In [39]:
import pickle

# Save the model to a file
with open("model.pkl", "wb") as file:
    pickle.dump(final_model, file)